### ISSUE TITLE
Equation numbering doesn't work as expected with "number-sections: false" in YML

### ISSUE THREAD

**Issue by mladenjovanovic** [nmfs-opensci/quarto_titlepages#10]
When using academic-static template, with "number-sections: false" in the YML, equations numbering still have section number beforehand (i.e., 0.1, 0.2, 0.3) instead of integer (i.e., 1, 2, 3). This is not the case for figures. I have attached the files to reproduce the results.
[files.zip](https://github.com/nmfs-opensci/quarto_titlepages/files/9439726/Archive.zip)

**Comment by eeholmes** [comment]
@mladenjovanovic document class `scrbook` doesn't work with `number-sections: false`. It seems to be something just for `scrartcl` class:

```
    documentclass: scrartcl
    number-sections: false
```

If you need the `scrbook` class (for other features), then you'll need to figure out how to turn off section numbering for that class.  https://ctan.org/pkg/scrbook?lang=en

This is actually why I don't like setting the latex class and package options with the YAML variables. It can be really hard to figure out example what latex command is being issued. For `number-sections: false`, you'd have to dig into the pandoc templates that Quarto is using to figure it out. But clearly it is a command that only works correctly for `scrartcl` and I wouldn't assume that it would work correctly for any other latex document class.

**Comment by eeholmes** [comment]
To do:

- [] Check that `number-sections: false` is only used for `scrartcl` in templates
- [] Add note about this in documentation

**Comment by mladenjovanovic** [comment]
Thanks, @eeholmes. We who do not know latex prefer the YML, but I guess you are completely correct. Thanks for answering my issue. Keep up the great work
