### ISSUE TITLE
Langage setting issue

### ISSUE THREAD

**Issue by oousmane** [nmfs-opensci/quarto_titlepages#12]
I encountered langage. setting issue with templates. setting langage to French like that 

---
title: "foooo"
lang: fr
format:
  titlepage-pdf:
    titlepage: academic-static
    documentclass: scrartcl
    toc: true
    toc-depth: 3
    lof: true
    lot: true
---

or like that 
---
title: "foooo"
lang: fr
format:
  titlepage-pdf:
    titlepage: academic-static
    documentclass: scrartcl
    toc: true
    toc-depth: 3
    lof: true
    lot: true
    lang: fr
---
 lead me to that issue 
compilation failed- error
LaTeX Error: Option clash for package babel.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.138 \fi

I changed langage into pando.tex but no way to fix things. using static template. I get the same issue with dynamic one

**Comment by eeholmes** [comment]
Sorry about that! There was a babel conflict left over from my example code in the pandoc.tex file. I've removed that. 

Note at the bottom of `example.qmd` there is 
```
    include-in-header: |
      text:
        % delete. this is for the example w CZ diacritics
        \usepackage{babel}
        \babelprovide[import]{czech}
```

This is just so my example with CZ diacritics works and shows how you might import other languages. You can delete this and use `lang: fr` in the header. Or leave it in. It won't cause problems with `lang: fr` now.
