### ISSUE TITLE
YAML validation fails when running `quarto install extension nmfs-opensci/quarto_titlepages`

### ISSUE THREAD

**Issue by martintburgess** [nmfs-opensci/quarto_titlepages#15]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the debugging guide: <https://github.com/Openscapes/2021-noaa-nmfs/wiki/2-Issues-and-Project-Boards>
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed.

### Description

Thanks for this extension - letting you know I get the following error when running `quarto install extension nmfs-opensci/quarto_titlepages` in an existing quarto project. 

```
ERROR: YAML Validation Failed

In file ../../../../var/folders/p8/nkpb6m7j62jg8x0vsrjhmm700000gn/T/quarto-sessione08e97a1/29852a34/c8327ff5/archive/quarto_titlepages-main/_extensions/titlepage/_extension.yml
(line 3, columns 10--13) Key version has value 3.2, which must be a string that satisfies regex "^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
2: author: Eli Holmes
3: version: 3.2
            ~~~
4: contributes:
✖ The value 3.2 is number.
ℹ The error happened in location version.
```

### Steps to Reproduce

1. Open existing quarto directory
2. Run `quarto install extension nmfs-opensci/quarto_titlepages` 

**Expected behavior:**

No error

**Actual behavior:**

Above error.

**Reproduces how often:**

100% of tries

### Versions

Quarto version `1.1.251` running on latest Mac OS X

### Additional Information

Nothing further to add.

**Comment by eeholmes** [comment]
Thanks! I hadn't updated my Quart to v1.2 and now it requires version numbers to be 3 numbers so threw an error for 
```
version: 3.2
```
I updated to 
```
version: 3.2.1
```

**Comment by martintburgess** [comment]
Thanks for fixing so quickly!
