### ISSUE TITLE
YAML error in rendering example.qmd

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [nmfs-opensci/quarto_titlepages#29]
I have had trouble rendering the `example.qmd` script in quarto_titlepages, apparently because of a YAML error. Here is my system/software info:

* `quarto --version` : 0.9.566
* Tell us what operating system you are on: Windows 10 Enterprise, OS build 19044.2130

I run into this error when rendering example.qmd from my RStudio (using the "Render" button)
* `tex --version` returns MixTex-TeX 4.4 (MikTeX 22.3)

### Description
When I try to render example.qmd, I get the following YAML error in the Render tab:
![image](https://user-images.githubusercontent.com/73858992/200085042-c1e3ff9a-9d0b-41c7-9534-477fd4f0e4eb.png)

I would troubleshoot more but... don't really know anything about yaml and am slightly scared of it. So this is as much as I've got! I think this may be related to a TeX package I need to get that `scrbook` format or something.

### Steps to replicate
- clone quarto_titlepages repo
- open example.qmd in RStudio
- click "Render" at the top of the RStudio console

**Comment by eeholmes** [comment]
Your Quarto version is very old. Current version is 1.2. I think you need to update Quarto. Note if you update RStudio, you should get Quarto version 1.1 which is enough.

Quarto comes with `scrbook` so you don't need to install that. Quarto should also install tinytex.

**Comment by eeholmes** [comment]
Also by the way, MixTex-TeX 4.4 (MikTeX 22.3) will likely cause you frustration when rendering PDFs in Quarto.  Try installing tinytex.  You can install from the R command line.  Instructions here: https://yihui.org/tinytex/

**Comment by MargaretSiple-NOAA** [comment]
OK -- I installed both but I may need to update RStudio as you mentioned to get the quarto update; when I install the newest version it shows up as version 1.2 in my Packages tab, but when I put `quarto --version` in the console it still gives me 0.9.566. I guess I will update after getting some help from IT.

**Comment by eeholmes** [comment]
The 1.2 that you see in the Packages tab is the quarto R package; same name, different thing (<cry>). For some reason when you installed Quarto, it didn't get rid of the old one. You'll probably have to figure out how to delete/uninstall 0.9.566.
